name: Asana Parent Task Date Sync

on:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1:00 AM UTC
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  run-sync-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run date sync script
        env:
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
          PROJECT_GID: ${{ secrets.ASANA_PROJECT_GID }}
        run: python asana_date_sync.py
