name: Asana Parent Task Date Sync

on:
  # Trigger 1: Runs on a schedule
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

  # Trigger 2: Allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  run-sync-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run date sync script
        env:
          ASANA_PAT: ${{ secrets.ASANA_PAT }}
          PROJECT_GID: ${{ secrets.PROJECT_GID }}
        # This line is now changed back to run your main script.
        run: python asana_date_sync.py
